server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.182.7:3306/localtest
    username: root
    password: 123

mybatis:
  type-aliases-package: com.hine.entity
